# Programa de tabuada
import time
n = int(input('Digite um número: '))
print(f'A tabuada de {n} é :')
time.sleep(1)
print('-'*15)
print(f'{n} x { 1} ={n:2}')
print(f'{n} x { 2} ={n*2:2}')
print(f'{n} x { 3} ={n*3:2}')
print(f'{n} x { 4} ={n*4:2}')
print(f'{n} x { 5} ={n*5}')
print(f'{n} x { 6} ={n*6}')
print(f'{n} x { 7} ={n*7}')
print(f'{n} x { 8} ={n*8}')
print(f'{n} x { 9} ={n*9}')
print(f'{n} x {10}={n*10}')
print('-'*15)
